SELECT 
ID_RESULTADO,
ID_LOTERIA,
ID_SORTEOHR,
ID_ANIMAL,
CODIGOANIMAL,
FECHA, 
ESTATUS,
IDTICKET,
CODIGODTK,
MONTO,
PREMIO,
ESTATUSDTK,
MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC') AS PAGAR
FROM TBL_RESULTADOS 
INNER JOIN TBL_TICKET ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL <> CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '28-10-2017' AND ESTATUS <> 'XS';

UPDATE U
 SET U.PREMIO = MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC'),
 U.ESTATUSDTK = 'PE' 
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL = CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '28-10-2017' AND ESTATUS <> 'XS';



/* ACTUALIZO TICKET DETALLE */

UPDATE C
 SET C.PREMIOS = U.MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC'),
 C.ESTATUSTK = 'PE',
 C.DIFERENCIA = C.DIFERENCIA -  U.MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC')
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL = CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '28-10-2017' AND ESTATUS <> 'XS';

SELECT * FROM TBL_DTICKET;
SELECT * FROM TBL_TICKET WHERE ESTATUSTK = 'PE'







/* ACTUALIZO TICKET PERDEDOR MAL CARGADOS */

UPDATE C
 SET C.PREMIOS = 0,
 C.ESTATUSTK = 'PP',
 C.DIFERENCIA = C.TOTALPAGADO
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL <> CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '30-10-2017' AND ESTATUS <> 'XS';


/* ACTUALIZO TICKETS DETALLES PERDEDORES MAL CARGADOS */
UPDATE U
 SET U.PREMIO = 0,
 U.ESTATUSDTK = 'PP' 
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL <> CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '30-10-2017' AND ESTATUS <> 'XS';

/* ACTUALIZO DETALLE GANADOR */
UPDATE U
 SET U.PREMIO = MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC'),
 U.ESTATUSDTK = 'PE' 
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL = CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '30-10-2017' AND ESTATUS <> 'XS';

/* ACTUALIZO TICKET GANADOR */

UPDATE C
 SET C.PREMIOS = U.MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC'),
 C.ESTATUSTK = 'PE',
 C.DIFERENCIA = C.DIFERENCIA -  U.MONTO * (SELECT MULTIPLICADOR FROM TBL_BANCA WHERE ESTATUS = 'AC')
FROM TBL_RESULTADOS AS A 
INNER JOIN TBL_TICKET AS C ON 
ID_LOTERIA = IDSORTEOTK AND
ID_SORTEOHR = IDHRTK AND
FECHATQ = FECHA 
INNER JOIN 
TBL_DTICKET AS U ON
IDTICKET = IDTICKETDTR AND 
CODIGOANIMAL = CODIGODTK AND 
FECHADTK = FECHA
WHERE FECHA = '30-10-2017' AND ESTATUS <> 'XS';