#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jbanimalitosv2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Loterias")]
	public partial class CLS_LINQ_ANMLTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTBL_ANIMALITOS(TBL_ANIMALITOS instance);
    partial void UpdateTBL_ANIMALITOS(TBL_ANIMALITOS instance);
    partial void DeleteTBL_ANIMALITOS(TBL_ANIMALITOS instance);
    partial void InsertTBL_DTICKET(TBL_DTICKET instance);
    partial void UpdateTBL_DTICKET(TBL_DTICKET instance);
    partial void DeleteTBL_DTICKET(TBL_DTICKET instance);
    partial void InsertTBL_ESTATUS(TBL_ESTATUS instance);
    partial void UpdateTBL_ESTATUS(TBL_ESTATUS instance);
    partial void DeleteTBL_ESTATUS(TBL_ESTATUS instance);
    partial void InsertTBL_HORARIOS(TBL_HORARIOS instance);
    partial void UpdateTBL_HORARIOS(TBL_HORARIOS instance);
    partial void DeleteTBL_HORARIOS(TBL_HORARIOS instance);
    partial void InsertTbl_SORTEO(Tbl_SORTEO instance);
    partial void UpdateTbl_SORTEO(Tbl_SORTEO instance);
    partial void DeleteTbl_SORTEO(Tbl_SORTEO instance);
    partial void InsertTBL_TICKET(TBL_TICKET instance);
    partial void UpdateTBL_TICKET(TBL_TICKET instance);
    partial void DeleteTBL_TICKET(TBL_TICKET instance);
    #endregion
		
		public CLS_LINQ_ANMLTDataContext() : 
				base(global::Jbanimalitosv2.Properties.Settings.Default.LoteriasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_LINQ_ANMLTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_LINQ_ANMLTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_LINQ_ANMLTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CLS_LINQ_ANMLTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_ANIMALITOS> TBL_ANIMALITOS
		{
			get
			{
				return this.GetTable<TBL_ANIMALITOS>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DTICKET> TBL_DTICKET
		{
			get
			{
				return this.GetTable<TBL_DTICKET>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ESTATUS> TBL_ESTATUS
		{
			get
			{
				return this.GetTable<TBL_ESTATUS>();
			}
		}
		
		public System.Data.Linq.Table<TBL_HORARIOS> TBL_HORARIOS
		{
			get
			{
				return this.GetTable<TBL_HORARIOS>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_SORTEO> Tbl_SORTEO
		{
			get
			{
				return this.GetTable<Tbl_SORTEO>();
			}
		}
		
		public System.Data.Linq.Table<TBL_TICKET> TBL_TICKET
		{
			get
			{
				return this.GetTable<TBL_TICKET>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TOTALES_GYP")]
		public int TOTALES_GYP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PR_DESDE", DbType="Date")] System.Nullable<System.DateTime> pR_DESDE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PR_HASTA", DbType="Date")] System.Nullable<System.DateTime> pR_HASTA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PR_TTV", DbType="Money")] ref System.Nullable<decimal> pR_TTV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PR_TTP", DbType="Money")] ref System.Nullable<decimal> pR_TTP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PR_STT", DbType="Money")] ref System.Nullable<decimal> pR_STT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pR_DESDE, pR_HASTA, pR_TTV, pR_TTP, pR_STT);
			pR_TTV = ((System.Nullable<decimal>)(result.GetParameterValue(2)));
			pR_TTP = ((System.Nullable<decimal>)(result.GetParameterValue(3)));
			pR_STT = ((System.Nullable<decimal>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ANIMALITOS")]
	public partial class TBL_ANIMALITOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDANIMALITOS;
		
		private System.Nullable<int> _IDSORTEOAN;
		
		private string _CODIGO;
		
		private string _NOMBRE_ANIMALITO;
		
		private string _COLOR;
		
		private string _COLUMNA;
		
		private string _ESTATUS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDANIMALITOSChanging(int value);
    partial void OnIDANIMALITOSChanged();
    partial void OnIDSORTEOANChanging(System.Nullable<int> value);
    partial void OnIDSORTEOANChanged();
    partial void OnCODIGOChanging(string value);
    partial void OnCODIGOChanged();
    partial void OnNOMBRE_ANIMALITOChanging(string value);
    partial void OnNOMBRE_ANIMALITOChanged();
    partial void OnCOLORChanging(string value);
    partial void OnCOLORChanged();
    partial void OnCOLUMNAChanging(string value);
    partial void OnCOLUMNAChanged();
    partial void OnESTATUSChanging(string value);
    partial void OnESTATUSChanged();
    #endregion
		
		public TBL_ANIMALITOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDANIMALITOS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDANIMALITOS
		{
			get
			{
				return this._IDANIMALITOS;
			}
			set
			{
				if ((this._IDANIMALITOS != value))
				{
					this.OnIDANIMALITOSChanging(value);
					this.SendPropertyChanging();
					this._IDANIMALITOS = value;
					this.SendPropertyChanged("IDANIMALITOS");
					this.OnIDANIMALITOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSORTEOAN", DbType="Int")]
		public System.Nullable<int> IDSORTEOAN
		{
			get
			{
				return this._IDSORTEOAN;
			}
			set
			{
				if ((this._IDSORTEOAN != value))
				{
					this.OnIDSORTEOANChanging(value);
					this.SendPropertyChanging();
					this._IDSORTEOAN = value;
					this.SendPropertyChanged("IDSORTEOAN");
					this.OnIDSORTEOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="VarChar(2)")]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_ANIMALITO", DbType="VarChar(50)")]
		public string NOMBRE_ANIMALITO
		{
			get
			{
				return this._NOMBRE_ANIMALITO;
			}
			set
			{
				if ((this._NOMBRE_ANIMALITO != value))
				{
					this.OnNOMBRE_ANIMALITOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_ANIMALITO = value;
					this.SendPropertyChanged("NOMBRE_ANIMALITO");
					this.OnNOMBRE_ANIMALITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLOR", DbType="VarChar(1)")]
		public string COLOR
		{
			get
			{
				return this._COLOR;
			}
			set
			{
				if ((this._COLOR != value))
				{
					this.OnCOLORChanging(value);
					this.SendPropertyChanging();
					this._COLOR = value;
					this.SendPropertyChanged("COLOR");
					this.OnCOLORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COLUMNA", DbType="VarChar(1)")]
		public string COLUMNA
		{
			get
			{
				return this._COLUMNA;
			}
			set
			{
				if ((this._COLUMNA != value))
				{
					this.OnCOLUMNAChanging(value);
					this.SendPropertyChanging();
					this._COLUMNA = value;
					this.SendPropertyChanged("COLUMNA");
					this.OnCOLUMNAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="VarChar(1)")]
		public string ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DTICKET")]
	public partial class TBL_DTICKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDUNICO;
		
		private System.Nullable<long> _IDTICKETDTR;
		
		private string _CODIGODTK;
		
		private System.Nullable<double> _MONTO;
		
		private System.Nullable<double> _PREMIO;
		
		private string _ESTATUSDTK;
		
		private System.Nullable<System.DateTime> _FECHADTK;
		
		private System.Nullable<System.TimeSpan> _HORA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUNICOChanging(long value);
    partial void OnIDUNICOChanged();
    partial void OnIDTICKETDTRChanging(System.Nullable<long> value);
    partial void OnIDTICKETDTRChanged();
    partial void OnCODIGODTKChanging(string value);
    partial void OnCODIGODTKChanged();
    partial void OnMONTOChanging(System.Nullable<double> value);
    partial void OnMONTOChanged();
    partial void OnPREMIOChanging(System.Nullable<double> value);
    partial void OnPREMIOChanged();
    partial void OnESTATUSDTKChanging(string value);
    partial void OnESTATUSDTKChanged();
    partial void OnFECHADTKChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHADTKChanged();
    partial void OnHORAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORAChanged();
    #endregion
		
		public TBL_DTICKET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUNICO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDUNICO
		{
			get
			{
				return this._IDUNICO;
			}
			set
			{
				if ((this._IDUNICO != value))
				{
					this.OnIDUNICOChanging(value);
					this.SendPropertyChanging();
					this._IDUNICO = value;
					this.SendPropertyChanged("IDUNICO");
					this.OnIDUNICOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTICKETDTR", DbType="BigInt")]
		public System.Nullable<long> IDTICKETDTR
		{
			get
			{
				return this._IDTICKETDTR;
			}
			set
			{
				if ((this._IDTICKETDTR != value))
				{
					this.OnIDTICKETDTRChanging(value);
					this.SendPropertyChanging();
					this._IDTICKETDTR = value;
					this.SendPropertyChanged("IDTICKETDTR");
					this.OnIDTICKETDTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGODTK", DbType="VarChar(2)")]
		public string CODIGODTK
		{
			get
			{
				return this._CODIGODTK;
			}
			set
			{
				if ((this._CODIGODTK != value))
				{
					this.OnCODIGODTKChanging(value);
					this.SendPropertyChanging();
					this._CODIGODTK = value;
					this.SendPropertyChanged("CODIGODTK");
					this.OnCODIGODTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTO", DbType="Float")]
		public System.Nullable<double> MONTO
		{
			get
			{
				return this._MONTO;
			}
			set
			{
				if ((this._MONTO != value))
				{
					this.OnMONTOChanging(value);
					this.SendPropertyChanging();
					this._MONTO = value;
					this.SendPropertyChanged("MONTO");
					this.OnMONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREMIO", DbType="Float")]
		public System.Nullable<double> PREMIO
		{
			get
			{
				return this._PREMIO;
			}
			set
			{
				if ((this._PREMIO != value))
				{
					this.OnPREMIOChanging(value);
					this.SendPropertyChanging();
					this._PREMIO = value;
					this.SendPropertyChanged("PREMIO");
					this.OnPREMIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUSDTK", DbType="VarChar(2)")]
		public string ESTATUSDTK
		{
			get
			{
				return this._ESTATUSDTK;
			}
			set
			{
				if ((this._ESTATUSDTK != value))
				{
					this.OnESTATUSDTKChanging(value);
					this.SendPropertyChanging();
					this._ESTATUSDTK = value;
					this.SendPropertyChanged("ESTATUSDTK");
					this.OnESTATUSDTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHADTK", DbType="Date")]
		public System.Nullable<System.DateTime> FECHADTK
		{
			get
			{
				return this._FECHADTK;
			}
			set
			{
				if ((this._FECHADTK != value))
				{
					this.OnFECHADTKChanging(value);
					this.SendPropertyChanging();
					this._FECHADTK = value;
					this.SendPropertyChanged("FECHADTK");
					this.OnFECHADTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA
		{
			get
			{
				return this._HORA;
			}
			set
			{
				if ((this._HORA != value))
				{
					this.OnHORAChanging(value);
					this.SendPropertyChanging();
					this._HORA = value;
					this.SendPropertyChanged("HORA");
					this.OnHORAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ESTATUS")]
	public partial class TBL_ESTATUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDESTATUS;
		
		private string _CODESTATUS;
		
		private string _NOMESTATUS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDESTATUSChanging(int value);
    partial void OnIDESTATUSChanged();
    partial void OnCODESTATUSChanging(string value);
    partial void OnCODESTATUSChanged();
    partial void OnNOMESTATUSChanging(string value);
    partial void OnNOMESTATUSChanged();
    #endregion
		
		public TBL_ESTATUS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDESTATUS", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDESTATUS
		{
			get
			{
				return this._IDESTATUS;
			}
			set
			{
				if ((this._IDESTATUS != value))
				{
					this.OnIDESTATUSChanging(value);
					this.SendPropertyChanging();
					this._IDESTATUS = value;
					this.SendPropertyChanged("IDESTATUS");
					this.OnIDESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODESTATUS", DbType="VarChar(2)")]
		public string CODESTATUS
		{
			get
			{
				return this._CODESTATUS;
			}
			set
			{
				if ((this._CODESTATUS != value))
				{
					this.OnCODESTATUSChanging(value);
					this.SendPropertyChanging();
					this._CODESTATUS = value;
					this.SendPropertyChanged("CODESTATUS");
					this.OnCODESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMESTATUS", DbType="VarChar(20)")]
		public string NOMESTATUS
		{
			get
			{
				return this._NOMESTATUS;
			}
			set
			{
				if ((this._NOMESTATUS != value))
				{
					this.OnNOMESTATUSChanging(value);
					this.SendPropertyChanging();
					this._NOMESTATUS = value;
					this.SendPropertyChanged("NOMESTATUS");
					this.OnNOMESTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_HORARIOS")]
	public partial class TBL_HORARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHORA;
		
		private System.Nullable<int> _IDSORTEOHR;
		
		private System.Nullable<System.TimeSpan> _HORA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHORAChanging(int value);
    partial void OnIDHORAChanged();
    partial void OnIDSORTEOHRChanging(System.Nullable<int> value);
    partial void OnIDSORTEOHRChanged();
    partial void OnHORAChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORAChanged();
    #endregion
		
		public TBL_HORARIOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHORA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHORA
		{
			get
			{
				return this._IDHORA;
			}
			set
			{
				if ((this._IDHORA != value))
				{
					this.OnIDHORAChanging(value);
					this.SendPropertyChanging();
					this._IDHORA = value;
					this.SendPropertyChanged("IDHORA");
					this.OnIDHORAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSORTEOHR", DbType="Int")]
		public System.Nullable<int> IDSORTEOHR
		{
			get
			{
				return this._IDSORTEOHR;
			}
			set
			{
				if ((this._IDSORTEOHR != value))
				{
					this.OnIDSORTEOHRChanging(value);
					this.SendPropertyChanging();
					this._IDSORTEOHR = value;
					this.SendPropertyChanged("IDSORTEOHR");
					this.OnIDSORTEOHRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORA", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORA
		{
			get
			{
				return this._HORA;
			}
			set
			{
				if ((this._HORA != value))
				{
					this.OnHORAChanging(value);
					this.SendPropertyChanging();
					this._HORA = value;
					this.SendPropertyChanged("HORA");
					this.OnHORAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_SORTEO")]
	public partial class Tbl_SORTEO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SORTEO;
		
		private string _NOMBRE_SORTEO;
		
		private System.Nullable<double> _MINIMO;
		
		private System.Nullable<double> _MAXIMO;
		
		private System.Nullable<double> _PAGARE;
		
		private string _ESTATUS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SORTEOChanging(int value);
    partial void OnID_SORTEOChanged();
    partial void OnNOMBRE_SORTEOChanging(string value);
    partial void OnNOMBRE_SORTEOChanged();
    partial void OnMINIMOChanging(System.Nullable<double> value);
    partial void OnMINIMOChanged();
    partial void OnMAXIMOChanging(System.Nullable<double> value);
    partial void OnMAXIMOChanged();
    partial void OnPAGAREChanging(System.Nullable<double> value);
    partial void OnPAGAREChanged();
    partial void OnESTATUSChanging(string value);
    partial void OnESTATUSChanged();
    #endregion
		
		public Tbl_SORTEO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SORTEO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SORTEO
		{
			get
			{
				return this._ID_SORTEO;
			}
			set
			{
				if ((this._ID_SORTEO != value))
				{
					this.OnID_SORTEOChanging(value);
					this.SendPropertyChanging();
					this._ID_SORTEO = value;
					this.SendPropertyChanged("ID_SORTEO");
					this.OnID_SORTEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_SORTEO", DbType="VarChar(50)")]
		public string NOMBRE_SORTEO
		{
			get
			{
				return this._NOMBRE_SORTEO;
			}
			set
			{
				if ((this._NOMBRE_SORTEO != value))
				{
					this.OnNOMBRE_SORTEOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_SORTEO = value;
					this.SendPropertyChanged("NOMBRE_SORTEO");
					this.OnNOMBRE_SORTEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINIMO", DbType="Float")]
		public System.Nullable<double> MINIMO
		{
			get
			{
				return this._MINIMO;
			}
			set
			{
				if ((this._MINIMO != value))
				{
					this.OnMINIMOChanging(value);
					this.SendPropertyChanging();
					this._MINIMO = value;
					this.SendPropertyChanged("MINIMO");
					this.OnMINIMOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXIMO", DbType="Float")]
		public System.Nullable<double> MAXIMO
		{
			get
			{
				return this._MAXIMO;
			}
			set
			{
				if ((this._MAXIMO != value))
				{
					this.OnMAXIMOChanging(value);
					this.SendPropertyChanging();
					this._MAXIMO = value;
					this.SendPropertyChanged("MAXIMO");
					this.OnMAXIMOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGARE", DbType="Float")]
		public System.Nullable<double> PAGARE
		{
			get
			{
				return this._PAGARE;
			}
			set
			{
				if ((this._PAGARE != value))
				{
					this.OnPAGAREChanging(value);
					this.SendPropertyChanging();
					this._PAGARE = value;
					this.SendPropertyChanged("PAGARE");
					this.OnPAGAREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUS", DbType="VarChar(1)")]
		public string ESTATUS
		{
			get
			{
				return this._ESTATUS;
			}
			set
			{
				if ((this._ESTATUS != value))
				{
					this.OnESTATUSChanging(value);
					this.SendPropertyChanging();
					this._ESTATUS = value;
					this.SendPropertyChanged("ESTATUS");
					this.OnESTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_TICKET")]
	public partial class TBL_TICKET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDTICKET;
		
		private System.Nullable<int> _IDSORTEOTK;
		
		private System.Nullable<int> _IDHRTK;
		
		private System.Nullable<double> _TOTALPAGADO;
		
		private System.Nullable<double> _JUGADAS;
		
		private System.Nullable<double> _PREMIOS;
		
		private System.Nullable<double> _DIFERENCIA;
		
		private string _ESTATUSTK;
		
		private string _SERIAL;
		
		private System.Nullable<System.DateTime> _FECHATQ;
		
		private System.Nullable<System.TimeSpan> _HORATQ;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTICKETChanging(long value);
    partial void OnIDTICKETChanged();
    partial void OnIDSORTEOTKChanging(System.Nullable<int> value);
    partial void OnIDSORTEOTKChanged();
    partial void OnIDHRTKChanging(System.Nullable<int> value);
    partial void OnIDHRTKChanged();
    partial void OnTOTALPAGADOChanging(System.Nullable<double> value);
    partial void OnTOTALPAGADOChanged();
    partial void OnJUGADASChanging(System.Nullable<double> value);
    partial void OnJUGADASChanged();
    partial void OnPREMIOSChanging(System.Nullable<double> value);
    partial void OnPREMIOSChanged();
    partial void OnDIFERENCIAChanging(System.Nullable<double> value);
    partial void OnDIFERENCIAChanged();
    partial void OnESTATUSTKChanging(string value);
    partial void OnESTATUSTKChanged();
    partial void OnSERIALChanging(string value);
    partial void OnSERIALChanged();
    partial void OnFECHATQChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHATQChanged();
    partial void OnHORATQChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHORATQChanged();
    #endregion
		
		public TBL_TICKET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTICKET", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDTICKET
		{
			get
			{
				return this._IDTICKET;
			}
			set
			{
				if ((this._IDTICKET != value))
				{
					this.OnIDTICKETChanging(value);
					this.SendPropertyChanging();
					this._IDTICKET = value;
					this.SendPropertyChanged("IDTICKET");
					this.OnIDTICKETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSORTEOTK", DbType="Int")]
		public System.Nullable<int> IDSORTEOTK
		{
			get
			{
				return this._IDSORTEOTK;
			}
			set
			{
				if ((this._IDSORTEOTK != value))
				{
					this.OnIDSORTEOTKChanging(value);
					this.SendPropertyChanging();
					this._IDSORTEOTK = value;
					this.SendPropertyChanged("IDSORTEOTK");
					this.OnIDSORTEOTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHRTK", DbType="Int")]
		public System.Nullable<int> IDHRTK
		{
			get
			{
				return this._IDHRTK;
			}
			set
			{
				if ((this._IDHRTK != value))
				{
					this.OnIDHRTKChanging(value);
					this.SendPropertyChanging();
					this._IDHRTK = value;
					this.SendPropertyChanged("IDHRTK");
					this.OnIDHRTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALPAGADO", DbType="Float")]
		public System.Nullable<double> TOTALPAGADO
		{
			get
			{
				return this._TOTALPAGADO;
			}
			set
			{
				if ((this._TOTALPAGADO != value))
				{
					this.OnTOTALPAGADOChanging(value);
					this.SendPropertyChanging();
					this._TOTALPAGADO = value;
					this.SendPropertyChanged("TOTALPAGADO");
					this.OnTOTALPAGADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUGADAS", DbType="Float")]
		public System.Nullable<double> JUGADAS
		{
			get
			{
				return this._JUGADAS;
			}
			set
			{
				if ((this._JUGADAS != value))
				{
					this.OnJUGADASChanging(value);
					this.SendPropertyChanging();
					this._JUGADAS = value;
					this.SendPropertyChanged("JUGADAS");
					this.OnJUGADASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREMIOS", DbType="Float")]
		public System.Nullable<double> PREMIOS
		{
			get
			{
				return this._PREMIOS;
			}
			set
			{
				if ((this._PREMIOS != value))
				{
					this.OnPREMIOSChanging(value);
					this.SendPropertyChanging();
					this._PREMIOS = value;
					this.SendPropertyChanged("PREMIOS");
					this.OnPREMIOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIFERENCIA", DbType="Float")]
		public System.Nullable<double> DIFERENCIA
		{
			get
			{
				return this._DIFERENCIA;
			}
			set
			{
				if ((this._DIFERENCIA != value))
				{
					this.OnDIFERENCIAChanging(value);
					this.SendPropertyChanging();
					this._DIFERENCIA = value;
					this.SendPropertyChanged("DIFERENCIA");
					this.OnDIFERENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTATUSTK", DbType="VarChar(2)")]
		public string ESTATUSTK
		{
			get
			{
				return this._ESTATUSTK;
			}
			set
			{
				if ((this._ESTATUSTK != value))
				{
					this.OnESTATUSTKChanging(value);
					this.SendPropertyChanging();
					this._ESTATUSTK = value;
					this.SendPropertyChanged("ESTATUSTK");
					this.OnESTATUSTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERIAL", DbType="VarChar(50)")]
		public string SERIAL
		{
			get
			{
				return this._SERIAL;
			}
			set
			{
				if ((this._SERIAL != value))
				{
					this.OnSERIALChanging(value);
					this.SendPropertyChanging();
					this._SERIAL = value;
					this.SendPropertyChanged("SERIAL");
					this.OnSERIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHATQ", DbType="Date")]
		public System.Nullable<System.DateTime> FECHATQ
		{
			get
			{
				return this._FECHATQ;
			}
			set
			{
				if ((this._FECHATQ != value))
				{
					this.OnFECHATQChanging(value);
					this.SendPropertyChanging();
					this._FECHATQ = value;
					this.SendPropertyChanged("FECHATQ");
					this.OnFECHATQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORATQ", DbType="Time")]
		public System.Nullable<System.TimeSpan> HORATQ
		{
			get
			{
				return this._HORATQ;
			}
			set
			{
				if ((this._HORATQ != value))
				{
					this.OnHORATQChanging(value);
					this.SendPropertyChanging();
					this._HORATQ = value;
					this.SendPropertyChanged("HORATQ");
					this.OnHORATQChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
